In [46]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [47]:
df = pd.read_csv('Churn_Modelling.csv')

In [48]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [49]:
X = df.iloc[: , 3:13].values

In [50]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ..., 
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [51]:
y = df.iloc[: , 13].values

In [52]:
y

array([1, 0, 1, ..., 1, 1, 0])

In [53]:
from sklearn.preprocessing import LabelEncoder , OneHotEncoder
label_encoder_X_1 = LabelEncoder()
X[: , 1] = label_encoder_X_1.fit_transform(X[: , 1])

In [54]:
X

array([[619, 0, 'Female', ..., 1, 1, 101348.88],
       [608, 2, 'Female', ..., 0, 1, 112542.58],
       [502, 0, 'Female', ..., 1, 0, 113931.57],
       ..., 
       [709, 0, 'Female', ..., 0, 1, 42085.58],
       [772, 1, 'Male', ..., 1, 0, 92888.52],
       [792, 0, 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [55]:
label_encoder_X_2 = LabelEncoder()
X[: , 2] = label_encoder_X_2.fit_transform(X[: , 2])

In [56]:
X

array([[619, 0, 0, ..., 1, 1, 101348.88],
       [608, 2, 0, ..., 0, 1, 112542.58],
       [502, 0, 0, ..., 1, 0, 113931.57],
       ..., 
       [709, 0, 0, ..., 0, 1, 42085.58],
       [772, 1, 1, ..., 1, 0, 92888.52],
       [792, 0, 0, ..., 1, 0, 38190.78]], dtype=object)

In [57]:
onehotencoder = OneHotEncoder(categorical_features=[1])
X = onehotencoder.fit_transform(X).toarray()

In [58]:
X.astype(int)

array([[     1,      0,      0, ...,      1,      1, 101348],
       [     0,      0,      1, ...,      0,      1, 112542],
       [     1,      0,      0, ...,      1,      0, 113931],
       ..., 
       [     1,      0,      0, ...,      0,      1,  42085],
       [     0,      1,      0, ...,      1,      0,  92888],
       [     1,      0,      0, ...,      1,      0,  38190]])

In [59]:
X = X[:, 1:]

In [61]:
X.astype(int)

array([[     0,      0,    619, ...,      1,      1, 101348],
       [     0,      1,    608, ...,      0,      1, 112542],
       [     0,      0,    502, ...,      1,      0, 113931],
       ..., 
       [     0,      0,    709, ...,      0,      1,  42085],
       [     1,      0,    772, ...,      1,      0,  92888],
       [     0,      0,    792, ...,      1,      0,  38190]])

In [62]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(X , y , test_size = 0.2 , random_state = 0)

In [64]:
X_train.astype(int)

array([[     0,      1,    667, ...,      1,      0, 163830],
       [     1,      0,    427, ...,      1,      1,  57098],
       [     0,      0,    535, ...,      1,      0, 185630],
       ..., 
       [     0,      0,    738, ...,      1,      0, 181429],
       [     0,      1,    590, ...,      1,      1, 148750],
       [     1,      0,    623, ...,      1,      0, 118855]])

In [65]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [66]:
X_train

array([[-0.5698444 ,  1.74309049,  0.16958176, ...,  0.64259497,
        -1.03227043,  1.10643166],
       [ 1.75486502, -0.57369368, -2.30455945, ...,  0.64259497,
         0.9687384 , -0.74866447],
       [-0.5698444 , -0.57369368, -1.19119591, ...,  0.64259497,
        -1.03227043,  1.48533467],
       ..., 
       [-0.5698444 , -0.57369368,  0.9015152 , ...,  0.64259497,
        -1.03227043,  1.41231994],
       [-0.5698444 ,  1.74309049, -0.62420521, ...,  0.64259497,
         0.9687384 ,  0.84432121],
       [ 1.75486502, -0.57369368, -0.28401079, ...,  0.64259497,
        -1.03227043,  0.32472465]])

# Building the ANN

In [67]:
import keras

In [70]:
from keras.models import Sequential
from keras.layers import Dense #Randomly initialise the weights

In [71]:
classifier = Sequential()

In [74]:
#Create 1st hidden layer
classifier.add(Dense(input_dim = 11 , units = 6 , kernel_initializer = 'uniform' , activation='relu'))

In [75]:
#Create 2nd hidden layer
classifier.add(Dense(units = 6 , kernel_initializer = 'uniform' , activation='relu'))

In [76]:
#Create output layer
classifier.add(Dense(units = 1 , kernel_initializer = 'uniform' , activation='sigmoid'))
#activation = 'softmax' for more than one output

In [77]:
classifier.compile(optimizer='adam' , loss='binary_crossentropy' , metrics=['accuracy'])

In [78]:
classifier.fit(X_train , y_train , batch_size=10 , epochs=100)

Epoch 1/100
8000/8000 [==============================] - 5s 579us/step - loss: 0.4827 - acc: 0.7960
Epoch 2/100
8000/8000 [==============================] - 4s 483us/step - loss: 0.4294 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 4s 472us/step - loss: 0.4234 - acc: 0.7990
Epoch 4/100
8000/8000 [==============================] - 4s 479us/step - loss: 0.4193 - acc: 0.8254
Epoch 5/100
8000/8000 [==============================] - 4s 505us/step - loss: 0.4169 - acc: 0.8255
Epoch 6/100
8000/8000 [==============================] - 4s 478us/step - loss: 0.4149 - acc: 0.8292
Epoch 7/100
8000/8000 [==============================] - 4s 476us/step - loss: 0.4135 - acc: 0.8311
Epoch 8/100
8000/8000 [==============================] - 4s 483us/step - loss: 0.4120 - acc: 0.8312
Epoch 9/100
8000/8000 [==============================] - 4s 481us/step - loss: 0.4108 - acc: 0.8320
Epoch 10/100
8000/8000 [==============================] - 4s 475us/step - loss: 0.4099 - acc: 0.8344

8000/8000 [==============================] - 4s 446us/step - loss: 0.4005 - acc: 0.8347
Epoch 83/100
8000/8000 [==============================] - 4s 447us/step - loss: 0.4006 - acc: 0.8356
Epoch 84/100
8000/8000 [==============================] - 4s 451us/step - loss: 0.4002 - acc: 0.8350
Epoch 85/100
8000/8000 [==============================] - 4s 460us/step - loss: 0.4006 - acc: 0.8362
Epoch 86/100
8000/8000 [==============================] - 4s 449us/step - loss: 0.4009 - acc: 0.8350
Epoch 87/100
8000/8000 [==============================] - 4s 449us/step - loss: 0.4005 - acc: 0.8352
Epoch 88/100
8000/8000 [==============================] - 4s 466us/step - loss: 0.4006 - acc: 0.8342
Epoch 89/100
8000/8000 [==============================] - 4s 454us/step - loss: 0.4005 - acc: 0.8350
Epoch 90/100
8000/8000 [==============================] - 4s 450us/step - loss: 0.3997 - acc: 0.8337
Epoch 91/100
8000/8000 [==============================] - 4s 475us/step - loss: 0.4009 - acc: 0.8340
Epo

In [79]:
y_pred = classifier.predict(X_test)

In [80]:
y_pred

array([[ 0.22667748],
       [ 0.37607485],
       [ 0.19435899],
       ..., 
       [ 0.16717382],
       [ 0.18196474],
       [ 0.11010176]], dtype=float32)

In [81]:
for i in range(0 , len(y_pred)):
    if y_pred[i][0] > 0.5 : 
        y_pred[i][0] = 1.0
    else:
        y_pred[i][0] = 0.0

In [82]:
y_pred

array([[ 0.],
       [ 0.],
       [ 0.],
       ..., 
       [ 0.],
       [ 0.],
       [ 0.]], dtype=float32)

In [83]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test , y_pred)

In [85]:
cm

array([[1537,   58],
       [ 255,  150]])

In [86]:
accuracy = (1537 + 150) / (255 + 58 + 1537 + 150)

In [88]:
accuracy

0.8435

# Prediction of a new customer
-  Geography: France
-  Credit Score: 600
-  Gender: Male
-  Age: 40 years old
-  Tenure: 3 years
-  Balance: 60000 
-  Number of Products: 2
-  Does this customer have a credit card ? Yes
-  Is this customer an Active Member: Yes
-  Estimated Salary: 50000

In [91]:
new_prediction = classifier.predict(sc.transform(np.array([[0.0 , 0 , 600 , 1 , 40 , 3 , 60000 , 2 , 1 , 1 , 50000]])))

In [92]:
new_prediction

array([[ 0.08657349]], dtype=float32)